---
- name: Creates directory
  become: yes
  file:
    path: ~/ubuntu/web
    state: directory
- name: Extract the artifact
  become: yes
  unarchive:
    src: '~/project/artifact.tar.gz'
    dest: '~/ubuntu/web'
- name: Start the web app
  become: yes
  shell: |
    cd ~/ubuntu/web
    npm install
    pm2 stop default
    pm2 start npm -- start
