---
- name: Creates directory
  become: true
  file:
    path: /home/ubuntu/web
    state: directory
- name: Extract the artifact
  become: true
  unarchive:
    src: '~/project/artifact.tar.gz'
    dest: '/home/ubuntu/web'
- name: Start the web app
  become: true
  shell: |
    cd /home/ubuntu/web
    ls
    npm install
    pm2 stop default
    pm2 start npm -- start
